Updating files

diff --git a/infra/Vagrantfile-openstack-controller-bionic b/infra/Vagrantfile-openstack-controller-bionic
--- a/infra/Vagrantfile-openstack-controller-bionic
+++ b/infra/Vagrantfile-openstack-controller-bionic
@@ -37,7 +37,7 @@ Vagrant.configure("2") do |config|
   # Create a public network, which generally matched to bridged network.
   # Bridged networks make the machine appear as another physical device on
   # your network.
-  config.vm.network "public_network", bridge: "eno1"
+#  config.vm.network "public_network", bridge: "eno1"
   config.vm.network "public_network", ip: "10.0.0.11"
 
   # Share an additional folder to the guest VM. The first argument is
@@ -65,8 +65,15 @@ Vagrant.configure("2") do |config|
   # Enable provisioning with a shell script. Additional provisioners such as
   # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
   # documentation for more information about their specific syntax and use.
-  # config.vm.provision "shell", inline: <<-SHELL
-  #   apt-get update
-  #   apt-get install -y apache2
-  # SHELL
+  config.vm.provision "shell", inline: <<-SHELL
+    echo "NECOS: git cloning necos.git"
+    git clone https://github.com/dcomp-leris/necos.git --quiet
+    if [ $? -ne 0 ]; then echo "NECOS: error"; fi
+
+    echo "NECOS: apt upgrading"
+    bash necos/infra/apt.sh
+
+    echo "NECOS: coping /etc/hosts"
+    sudo cp necos/infra/hosts /etc/
+  SHELL
 end
