updating master

diff --git a/infra/Vagrantfile-openstack-bionic b/infra/Vagrantfile-openstack-bionic
--- a/infra/Vagrantfile-openstack-bionic
+++ b/infra/Vagrantfile-openstack-bionic
@@ -85,4 +85,35 @@ Vagrant.configure("2") do |config|
     SHELL
   end
 ############### end compute1 block ###############
+
+############### start compute2 block ###############
+  config.vm.define "compute2" do |compute2|
+    compute2.vm.box = "ubuntu/bionic64"
+    compute2.vm.hostname = 'compute2'
+    compute2.vm.network "public_network", ip: "10.0.0.32"
+    compute2.vm.network "public_network"
+    compute2.vm.synced_folder ".", "/home/vagrant/"
+
+    compute2.vm.provider "virtualbox" do |vb|
+      vb.memory = "2048"
+      vb.cpus = "2"
+    end
+  
+    compute2.vm.provision "shell", inline: <<-SHELL
+      echo "NECOS: git cloning necos.git"
+      git clone https://github.com/dcomp-leris/necos.git --quiet
+      if [ $? -ne 0 ]; then echo "NECOS: error"; fi
+
+      echo "NECOS: apt upgrading"
+      bash necos/infra/apt.sh
+
+      echo "NECOS: coping /etc/hosts"
+      sudo cp necos/infra/hosts /etc/
+
+      echo "NECOS: moving log files"
+      bash necos/infra/move.sh
+    SHELL
+  end
+############### end compute2 block ###############
+
 end
