Vagrant file new

diff --git a/vagrant/Vagrantfile b/vagrant/Vagrantfile
--- a/vagrant/Vagrantfile
+++ b/vagrant/Vagrantfile
@@ -1,24 +1,32 @@
 # -*- mode: ruby -*-
 # vi: set ft=ruby :
 
+#Configuration Variables !
+controllerSlice1IP = "10.0.0.11"
+computeSlice1IP = "10.0.0.31"
+passwordSlice1 = "secret"
+controllerSlice2IP = "11.0.0.11"
+computeSlice2IP = "11.0.0.31"
+passwordSlice2 = "secret"
+numberEnv = "2"
+
 ENV["LC_ALL"] = "en_US.UTF-8"
 
 Vagrant.configure("2") do |config|
-  
 ############### start controller block ###############
-  config.vm.define "controller" do |controller|
-    controller.vm.box = "ubuntu/bionic64"
-    controller.vm.hostname = 'controller'
-    controller.vm.network "private_network", ip: "10.0.0.11"
-    controller.vm.network "public_network"
+  config.vm.define "controllerSlice1" do |controllerSlice1|
+    controllerSlice1.vm.box = "ubuntu/bionic64"
+    controllerSlice1.vm.hostname = 'controllerSlice1'
+    controllerSlice1.vm.network "private_network", ip: controllerSlice1IP
+    controllerSlice1.vm.network "public_network"
 
-    controller.vm.provider "virtualbox" do |vb|
+    controllerSlice1.vm.provider "virtualbox" do |vb|
       vb.memory = "6144"
       vb.cpus = "2"
       #vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
     end
   
-    controller.vm.provision "shell", inline: <<-SHELL
+    controllerSlice1.vm.provision "shell", inline: <<-SHELL
       echo "[NECOS] git cloning necos.git"
       git clone -b rocky https://github.com/dcomp-leris/necos.git --quiet
       if [ $? -ne 0 ]; then echo "[NECOS] error"; fi
@@ -73,19 +81,129 @@ Vagrant.configure("2") do |config|
 ############### end controller block ###############
 
 ############### start compute1 block ###############
-  config.vm.define "compute1" do |compute1|
-    compute1.vm.box = "ubuntu/bionic64"
-    compute1.vm.hostname = 'compute1'
-    compute1.vm.network "private_network", ip: "10.0.0.31"
-    compute1.vm.network "public_network"
+  config.vm.define "computeSlice1" do |computeSlice1|
+    computeSlice1.vm.box = "ubuntu/bionic64"
+    computeSlice1.vm.hostname = 'computeSlice1'
+    computeSlice1.vm.network "private_network", ip: "10.0.0.31"
+    computeSlice1.vm.network "public_network"
 
-    compute1.vm.provider "virtualbox" do |vb|
+    computeSlice1.vm.provider "virtualbox" do |vb|
       vb.memory = "2048"
       vb.cpus = "2"
       #vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
     end
   
-    compute1.vm.provision "shell", inline: <<-SHELL
+    computeSlice1.vm.provision "shell", inline: <<-SHELL
+      echo "[NECOS] git cloning necos.git"
+      git clone -b rocky https://github.com/dcomp-leris/necos.git --quiet
+      if [ $? -ne 0 ]; then echo "[NECOS] error"; fi
+      chown -R vagrant.vagrant necos
+
+      echo "[NECOS] apt upgrading"
+      bash necos/vagrant/apt.sh
+
+      echo "[NECOS] coping /etc/hosts"
+      sudo cp necos/vagrant/hosts /etc/
+
+      echo "[NECOS] installing chrony"
+      bash necos/vagrant/chrony-client.sh
+
+      echo "[NECOS] installing nova"
+      bash necos/vagrant/nova-compute.sh 10.0.0.31
+
+      echo "[NECOS] installing neutron"
+      bash necos/vagrant/neutron-compute.sh 10.0.0.31
+
+      echo "[NECOS] installing ceilometer"
+      bash necos/vagrant/ceilometer-compute.sh
+
+      echo "[NECOS] moving log files"
+      bash necos/vagrant/move.sh
+    SHELL
+  end
+############### end compute Slice 1 block ###############
+end	
+############### start controller Slice 2 block ###############
+  config.vm.define "controllerSlice2" do |controllerSlice2|
+    controllerSlice2.vm.box = "ubuntu/bionic64"
+    controllerSlice2.vm.hostname = 'controllerSlice2'
+    controllerSlice2.vm.network "private_network", ip: controllerSlice2IP
+    controllerSlice2.vm.network "public_network"
+
+    controllerSlice2.vm.provider "virtualbox" do |vb|
+      vb.memory = "6144"
+      vb.cpus = "2"
+      #vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
+    end
+  
+    controllerSlice2.vm.provision "shell", inline: <<-SHELL
+      echo "[NECOS] git cloning necos.git"
+      git clone -b rocky https://github.com/dcomp-leris/necos.git --quiet
+      if [ $? -ne 0 ]; then echo "[NECOS] error"; fi
+      chown -R vagrant.vagrant necos
+
+      echo "[NECOS] apt upgrading"
+      bash necos/vagrant/apt.sh
+
+      echo "[NECOS] coping /etc/hosts"
+      sudo cp necos/vagrant/hosts /etc/
+
+      echo "[NECOS] installing chrony"
+      bash necos/vagrant/chrony.sh
+
+      echo "[NECOS] installing mariadb"
+      bash necos/vagrant/mariadb.sh
+
+      echo "[NECOS] installing rabbitmq"
+      bash necos/vagrant/rabbitmq.sh
+
+      echo "[NECOS] installing memcached"
+      bash necos/vagrant/memcached.sh
+
+      echo "[NECOS] installing etcd"
+      bash necos/vagrant/etcd.sh
+
+      echo "[NECOS] installing keystone"
+      bash necos/vagrant/keystone.sh
+
+      echo "[NECOS] installing glance"
+      bash necos/vagrant/glance.sh
+
+      echo "[NECOS] installing nova"
+      bash necos/vagrant/nova.sh
+
+      echo "[NECOS] installing neutron"
+      bash necos/vagrant/neutron.sh
+
+      echo "[NECOS] installing horizon"
+      bash necos/vagrant/horizon.sh
+
+      echo "[NECOS] installing gnocchi"
+      bash necos/vagrant/gnocchi.sh
+
+      echo "[NECOS] installing ceilometer"
+      bash necos/vagrant/ceilometer.sh
+
+      echo "[NECOS] moving log files"
+      bash necos/vagrant/move.sh
+    SHELL
+  end
+############### end controller block ###############
+
+############### start compute1 block ###############
+  config.vm.define "computeSlice2" do |computeSlice2|
+    computeSlice2.vm.box = "ubuntu/bionic64"
+    computeSlice2.vm.hostname = 'computeSlice2'
+    computeSlice2.vm.network "private_network", ip: "11.0.0.31"
+    computeSlice2.vm.network "public_network"
+
+    computeSlice2.vm.provider "virtualbox" do |vb|
+      vb.memory = "2048"
+      vb.cpus = "2"
+      #vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
+    end
+  
+    computeSlice2.vm.provision "shell", inline: <<-SHELL
       echo "[NECOS] git cloning necos.git"
       git clone -b rocky https://github.com/dcomp-leris/necos.git --quiet
       if [ $? -ne 0 ]; then echo "[NECOS] error"; fi
@@ -114,5 +232,7 @@ Vagrant.configure("2") do |config|
     SHELL
   end
 ############### end compute1 block ###############
+end	
 
-end
+
+
